Repository UOSTime/UOSTime-Client, pull requests merged in 2021-08, with the labels that each got.

#61 [NO ISSUE] Footer 중앙 정렬 실패 이슈 해결
  package.json
  src/components/Footer.jsx
Labels: bug

#60 [#12] 메인 페이지 작성
  .eslintrc.json
  package.json
  src/App.jsx
  src/states/Lecture.js
  src/states/TimeTable.js
  src/states/Timetable.js
  src/utils/styles/Font.js
  src/utils/time.js
  src/utils/timetable.js
  src/views/Timetable.jsx
  src/views/login/SignUp.jsx
  src/views/login/index.jsx
  src/views/timetable/LectureList.jsx
  src/views/timetable/LectureListItem.jsx
  src/views/timetable/SearchBar.jsx
  src/views/timetable/SettingDialog.jsx
  src/views/timetable/ShareDialog.jsx
  src/views/timetable/Timetable.jsx
  src/views/timetable/TimetableCard.jsx
  src/views/timetable/TimetableCardList.jsx
  src/views/timetable/index.jsx
Labels: feature

#63 [NO ISSUE] 공지사항 삭제 API 변경 대응
  .eslintrc.json
  src/views/admin/NoticeList.jsx
Labels: feature

#64 [#35] 헤더 구현
  package.json
  src/components/Header.jsx
Labels: feature

#65 [NO ISSUE] 공지사항 API 및 API util 변경 대응
  src/utils/api.js
  src/views/admin/AddNoticeDialog.jsx
  src/views/admin/NoticeList.jsx
  src/views/notice/index.jsx
Labels: feature

#67 [#66] 로그인/회원가입 및 사용자 인증 개선
  src/App.jsx
  src/utils/api.js
  src/utils/socket.js
  src/views/login/FindId.jsx
  src/views/login/FindPw.jsx
  src/views/login/Logo.jsx
  src/views/login/SignUp.jsx
  src/views/login/index.jsx
  src/views/timetable/index.jsx
Labels: feature, refactoring
